name: Generate design tokens

on:
  repository_dispatch:
    types: update-tokens

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create input JSON
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: ${{ github.event.client_payload.filename }}
          json: ${{ github.event.client_payload.tokens }}
          dir: 'input'

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "style: Update design tokens"
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: create-pull-request/patch
          delete-branch: false
          title: "Update design tokens"
          body: |
            Design tokens have been updated via Figma and need to be reviewed.
          labels: |
            design
            automated-pr
          assignees: Henrry-Maximo
          reviewers: Henrry-Maximo
          team-reviewers: |
            developers
          milestone: 1
          draft: false
